[package]
name = "cranelift-jit-demo"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/cranelift-jit-demo"
description = "Toy language implemented using cranelift-jit"
edition = "2018"

[dependencies]
cranelift = "0.73.0"
cranelift-module = "0.73.0"
cranelift-jit = "0.73.0"
peg = "0.7.0"
