[package]
name = "simplejit-demo"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/CraneStation/simplejit-demo"
description = "Toy language implemented using cranelift-simplejit"

[[bin]]
name = "toy"
path = "src/toy.rs"

[dependencies]
cranelift = "0.58.0"
cranelift-module = "0.58.0"
cranelift-simplejit = "0.58.0"
peg = "0.6"
