[package]
name = "simplejit-demo"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
build = "build.rs"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/CraneStation/simplejit-demo"
description = "Toy language implemented using cranelift-simplejit"

[[bin]]
name = "toy"
path = "src/toy.rs"

[dependencies]
cranelift = "0.25.0"
cranelift-module = "0.25.0"
cranelift-simplejit = "0.25.0"
peg = "0.5.4"

[build-dependencies]
peg = { version = "0.5.4" }
